---
- name: Create the MySQL databases
  mysql_db:
    name: "{{ item }}"
    state: present
    encoding: utf8
    collation: utf8_general_ci
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items:
  - "{{ mysql_express_db_name }}"

- name: Create a variable for MySQL user accounts
  set_fact:
    mysql_user_accounts:
      - name: "{{ mysql_express_username }}"
        password: "{{ mysql_express_password }}"
        priv: "{{ mysql_express_db_name }}.*:ALL"
      - name: "{{ mysql_readonly_username }}"
        password: "{{ mysql_readonly_password }}"
        priv: "*.*:CREATE VIEW,SELECT,SHOW VIEW"

- name: Create MySQL user accounts
  mysql_user:
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    host: localhost
    update_password: on_create
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  with_items: "{{ mysql_user_accounts|default([]) }}"
