---
- name: Add the Supervisord config for Node.js
  template:
    src: nodejs-express.ini.j2
    dest: /etc/supervisord/conf.d/nodejs-express.ini
    mode: 0644
    owner: root
    group: root
  notify: Reload Supervisord

- name: Start Supervisord
  service:
    name: supervisord
    state: started
    enabled: true
